clients:
  ImageId: ami-05c13eab67c5d8861
  InstanceType: r5.large
  BlockDeviceMappings:
    - DeviceName: '/dev/sdh'
      Ebs:
        VolumeSize: 16
        VolumeType: gp3

server:
  ImageId: ami-05c13eab67c5d8861
  InstanceType: r5.large
  BlockDeviceMappings:
    - DeviceName: '/dev/sdh'
      Ebs:
        VolumeSize: 16
        VolumeType: gp3